### ISSUE TITLE
后台启动activity失效

### ISSUE THREAD

**Issue by ITAnt** [WuLiKanHuaZ/KeepLive10#1]
你好，使用AppUtil.l()方法在后台启动activity，在SDK_INT小于30的设备上正常，在大于等于30（Android 11）的设备上拉起失败。

**Comment by isayWu** [comment]
找到解决办法了吗？

**Comment by isayWu** [comment]
> 你好，使用AppUtil.l()方法在后台启动activity，在SDK_INT小于30的设备上正常，在大于等于30（Android 11）的设备上拉起失败。

找到解决办法了吗？

**Comment by isayWu** [comment]
欢迎加我微信，一起交流： adreamising

**Comment by WuLiKanHuaZ** [comment]
这个启动代码忘记修改了，还有一种方案可以绕过限制，密码忘了，等有空上传过来



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年7月10日(周三) 下午2:27
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: Re: [WuLiKanHuaZ/KeepLive10] 后台启动activity失效 (Issue #1)




  
你好，使用AppUtil.l()方法在后台启动activity，在SDK_INT小于30的设备上正常，在大于等于30（Android 11）的设备上拉起失败。
  
找到解决办法了吗？

**Comment by isayWu** [comment]
> adreamising

能加我微信一起交流吗？感谢
微信号：  adreamising

**Comment by isayWu** [comment]
大佬，另外一种方案什么时候能上传呀？
